### ISSUE TITLE
Concatenate Pictures?

### ISSUE THREAD

**Issue by ChrisPenner** [jtdaugherty/vty#122]
Hello; I use vty in the [Rasa](https://github.com/chrispenner/rasa) text editor; at the moment I'm building out more advanced splits/views functionality and am finding some limitations in vty.

My use case is as follows:

Views/windows are represented as a Tree of buffers; each buffer knows how to render itself to an Image, then a recursive function resizes and uses `<|>` and `<->` to join all the images into a single block which is converted to a picture. This has worked great so far; however at this point I'm now adding the feature of allowing auto-complete menus and pop-up windows, which would be composited on top of the other images. As far as I can tell the proper way to do this is to convert the image into a picture and to add the overlay as a layer to the picture. Due to the recursive nature of the tree however; that would then require the ability to `<|>` and `<->` over pictures; OR to somehow do compositing over Images.

Are either of these things currently possible in vty? Or do you have other ideas? I think something like https://github.com/jtdaugherty/vty/issues/73 would also do the trick.

**Comment by jtdaugherty** [comment]
If I understand the problem, is it possible for you to delay the conversion from `[Image] -> Picture` until the very end of this process? It seems to me that such an approach would address this problem. I can think of another benefit, which is that it also defers choice of cursor until "composite time" (i.e. the conversion to `Picture`) which is probably something that you have to do anyway.

**Comment by ChrisPenner** [comment]
That's possible; could you help me understand what you mean?

How can I use `<|>` and `<->` on `[Image]`s? Do I just join everything over the base layer? And if so won't the relative position of the higher layers be thrown off by the time we convert to Picture? I suppose the tricky thing I'm having trouble with is how I position things relative to a given image in the resulting Picture without needing to keep the positioning information all the way along to do a `translate` or pad at the last minute.

**Comment by jtdaugherty** [comment]
Are you aware of the translation functions?

http://hackage.haskell.org/package/vty-5.15/docs/Graphics-Vty-Image.html#v:translate

Those can be used to create `Image`s so that they can be layered on top of others when making a `Picture`. I'm imagining that you'd make full-screen `Image`s using your recursive algorithm, then make additional `Image`s (one per context menu or whatever) and add those (in the desired order) to the final list of `Image`s, create a `Picture` from that list, then send to the terminal for rendering.

**Comment by ChrisPenner** [comment]
Yup I'm aware of translate thanks! You're right in your assumptions for the most part; except that that the images aren't the size of the entire screen; think of vim-splits, except that each split is completely independently rendered, each split can have overlays, but the overlays can't escape the bounds of the split. So each Split would be a Picture (consisting of a base layer and any number of overlays), but then I need to concatenate or join all of the Pictures (splits) to form one large picture which I render to screen.

Yes I could keep the composited images (on each split) separate from the base layer, then join the base layers and overlay them over the joined base image; but the trick then is that I need to keep track of each composite's position relative to its embedded view and translate it along the way. For instance if I have an overlay on the third split to the right then I need to shift the overlay over by the width of the other two splits before adding it as a layer since it was originally positioned relative to the image representing just its own split. It should be possible; but it's certainly less elegant than a notion of joining Pictures.

**Comment by jtdaugherty** [comment]
Okay. I think I understand now. It does sound like an ability to compose pictures horizontally and/or vertically would get you what you want.

Right now Pictures declare a cursor to be positioned in the terminal. What should happen if I have two pictures `a` and `b`, both with cursor position requests, and then I want to display `a <|> b`? Since Picture is intended to represent the final view rendered in the terminal and since only a single cursor is supported by the terminal, I don't think there is a clear answer to what concatenation means in the presence of multiple cursor positions. It's possible `Picture` is not the right abstraction for supporting this operation and that a new intermediate type is needed to make these operations possible (so cursor information can be excluded from layer concatenation considerations).

**Comment by ChrisPenner** [comment]
Yes I agree; I think it would make sense to have an intermediate representation; something like `LayeredImage` which provides compositing without needing to worry about Cursors yet; In fact even without an intermediate representation it should be possible to simply over-write parts of the base image with the overlaying image without rending down to SpanOps; something like `overlay :: Image -> Image -> Image` would do the trick for me!

I know this doesn't match everyone's use-case; but I actually don't use a vty's cursors at all; I handle them myself and display them using Attributes.

**Comment by jtdaugherty** [comment]
I don't think `overlay` is possible to implement given the current design, but I think something like `concatLayersWith :: (Image -> Image -> Image) -> [Image] -> [Image] -> [Image]` is probably feasible. I'm not sure when I'll have time to investigate this, so if you end up wanting to explore this then I'd be happy to consider patches if I haven't gotten to it yet.

**Comment by noughtmare** [comment]
About the cursor problem: Why not use fake cursors (e.g. just a space with some nice cursor style)? Then you can also easily define multiple cursors.

**Comment by jtdaugherty** [comment]
@noughtmare I'm not sure I understand your proposal. The issue here is not *how* to deal with multiple cursors (which is a matter of implementation) but *whether it makes sense*, which is a design question. The question I posed above still needs a good answer:

> ... Pictures declare a cursor to be positioned in the terminal. What should happen if I have two pictures `a` and `b`, both with cursor position requests, and then I want to display `a <|> b`?

As I mentioned above, a "picture" in Vty is *defined* as the end-state representation to be shown in the terminal, where at most one cursor placement is possible. While it's true that the library could support other use cases (such as multiple cursors), ultimately the library must also provide a way to select at most one of them for display.

**Comment by noughtmare** [comment]
> ultimately the library must also provide a way to select at most one of them for display.

What I mean is why can't we make multiple displayed cursors possible? Then the composition of two pirctures would just show both cursors. I know that that it then won't be possible to use the real actual terminal cursor, but we can fake it.

**Comment by jtdaugherty** [comment]
I have never encountered a terminal application with anything like multiple cursors and I think it would be surprising if the library let someone do this without opting into the behavior. I also think that it would be confusing to use such an application. I don't want Vty to make a potentially confusing situation easy to realize without deliberate effort.

With that said, I think that if anything is to be done with this ticket, it starts with leaving cursors in Pictures and making a new internal abstraction for dealing with collections of layers instead. It's still up to the application to choose the final cursor position that way, since it has to be decoupled from how the image gets produced.

**Comment by ChrisPenner** [comment]
@jtdaugherty I actually use multiple cursors in rasa, but as @noughtmare suggests I do this manually by keeping track of cursor state in my app and using Attributes to invert the colouring of the 'selected' text. Multiple cursors have complicated semantics and it's best to let the app layer handle them.

I agree with @jtdaugherty though, I think an interstitial representation to handle layers of images would be the way to go; or to pull out the idea of cursors entirely and leave that up to things like Brick (and Rasa) to handle on their own, but obviously that's a pretty major breaking change.

**Comment by ChrisPenner** [comment]
All that said, you can close this issue if you like; I haven't been actively working on Rasa in some time.

**Comment by jtdaugherty** [comment]
@ChrisPenner Okay, I'll close it for now. If you resume work on your project and this again becomes a priority for you, please feel free to re-open.
