### ISSUE TITLE
Support GPM

### ISSUE THREAD

**Issue by zenzike** [jtdaugherty/vty#144]
General Purpose Mouse (GPM) provides access to a mouse on linux virtual consoles. It would be great if vty could support it!

**Comment by jtdaugherty** [comment]
That would indeed be great. Looking around, it looks like the best way to do that would be to write bindings to the GPM C library. Right now there doesn't appear to be such a library on Hackage. While I don't have have to shave that particular yak, I'd be happy to work with someone who does.

So for now, since there is not immediately a path forward, I'm going to close this. But if you or anyone else wants to work on a binding to GMP and then talk about how to use it in Vty, please re-open!
