### ISSUE TITLE
Image from text with ANSI codes

### ISSUE THREAD

**Issue by emilaxelsson** [jtdaugherty/vty#151]
I noticed that ANSI color codes aren't understood properly when using `text` to create an image. (I tried it in Brick, but assume it's a Vty issue.) The codes are passed through, but the image is cropped strangely, presumably because code characters are treated as having the same width as ordinary characters.

[trackit](https://github.com/emilaxelsson/trackit) contains a [function](https://github.com/emilaxelsson/trackit/blob/bf18534/src/Main.hs#L90) for creating an image from a `Text` value containing ANSI codes:

```haskell
ansiImage :: Text -> Image
```

Would you be interested in including this function in vty?

The parser is quite limited, but it handles color and boldness. I don't really have the time to make a full ANSI parser, but could add support for more properties if and as needed.

**Comment by jtdaugherty** [comment]
I would be willing to add that function, but I'd like it to handle as much of the escape sequence feature set as possible: essentially, I'd want to make it so that `ansiImage` could handle anything one could make with an `Image`, and *maybe* cursor placement escapes (in that case it'd be `ansiImage :: Text -> (Image, Maybe (Int, Int))`). I'd also want it to include in its documentation a comprehensive list of features it supports and a big warning label that if you give it some text with other escapes it doesn't know about, the result is undefined when you actually embed the `Image` in a UI. :)

**Comment by emilaxelsson** [comment]
OK, I understand that a more full-featured function makes more sense for a mature package like Vty.

So, by "anything one could make with an `Image`", do you mean anything that's supported by `Attr`, or something more?

**Comment by jtdaugherty** [comment]
Yes, that's right, sorry for not being clearer - as much as possible supported by `Attr`, and documentation about what's not supported if it's not practical to support everything. (For example, I'm not sure it's important to worry about hyperlinking.)

**Comment by emilaxelsson** [comment]
OK, cool, I'll work towards that when I have time.

I'm closing this issue then and will make a fresh pull request when I have something ready.

**Comment by jtdaugherty** [comment]
Very cool - thank you!
