### ISSUE TITLE
feature request: keep ByteString (e.g. UTF8 encoded) type internally and write ByteString to terminal

### ISSUE THREAD

**Issue by clojj** [jtdaugherty/vty#166]
1) I think the doc-Text for `utf8Bytestring'` should read `Make an 'Image' from a UTF-8 encoded bytestring.` (this is the strict version, not lazy)

2) In my brick application, I would like to save resources and enhance performance by consistently using `ByteString` instead of `Text`. I was able to do this successfully, by using a ByteString-variant of brick's text-zipper and Markup-type/functions (which I implemented recently, using ByteString instead of Text).
But unfortunately `vty` will currently convert everything back to `Text` internally. 
Can this vty-function (and consequently also the internal data types of vty) be changed, so that vty never has to convert the given ByteString by means of `T.decodeUtf8` ?

Ofcourse we 'only' talk about the impact of `T.decodeUtf8`.... but in the case of larger files with many operations performed , I think this will have a measurable impact.

(from Module `Graphics.Vty.Image`)
```
-- | Make an 'Image' from a UTF-8 encoded lazy bytestring.
utf8Bytestring' :: Attr -> B.ByteString -> Image
utf8Bytestring' a bs = text' a (T.decodeUtf8 bs)
```

**Comment by jtdaugherty** [comment]
As for (1), thanks, that's now fixed in 38948b4c4f4f4133d7b869e9e4e340e58bea5914.

As for (2), that's not possible right now. The chief reason is that internally, `Text` is used in `Image`s because image operations need to inspect the image contents *as text* to determine character widths, etc., meaning that even if the image constructors carried around bytestrings, decodes would still be necessary to perform the various image operations (cropping, etc.). Furthermore, before I'd be willing to consider any kind of overhaul to change that, I'd need to be convinced that this was the *right* performance hotspot to address.

If you're having performance issues in your `vty`- or `brick`-based application, chances are good that there are more significant factors elsewhere that can be addressed, or other strategies that could be employed. I'd be happy to take a look at your source and see if I can spot anything that would help, if you want to share.

Thanks!
