### ISSUE TITLE
Investigate possibility of 24-bit color support

### ISSUE THREAD

**Issue by jtdaugherty** [jtdaugherty/vty#167]
https://gist.github.com/XVilka/8346728

**Comment by u-quark** [comment]
:+1: This would be really awesome to have!

**Comment by iko-deleted** [comment]
I'm in need of a project, so I think I'm going to work on this.

Since vty uses terminfo for rendering, it would only be able to render 24bit color on systems with terminfo>= 6.1 installed, barring a rewrite of the renderer to use something else.

I'm not familiar with vty internals, but from a quick glance at the code, it doesn't seem like it would be that hard to do. 

It's worth noting that the linked gist has been moved to a repository, which will presumably have more up-to-date information: https://github.com/termstandard/colors

**Comment by jtdaugherty** [comment]
@cjenn that's great news, thank you! If you haven't already read it, please check out [the Contributing info in the README](https://github.com/jtdaugherty/vty#contributing).

**Comment by iko-deleted** [comment]
I've got it working!

![Screenshot_2019-06-06_21-11-47](https://user-images.githubusercontent.com/47906531/59077749-842a7d00-88a1-11e9-9448-7f27704d7c32.png)

I still want to make some edits to the code+haddocks, and test some basic optimizations, but the majority of [the code](https://github.com/cjenn/vty/tree/directcolor) is complete.

This doesn't use terminfo for rendering; It just prints out color codes manually. As such, it's really bad at detecting terminal support for direct color, but should work across all terminals that have that support.

**Comment by jtdaugherty** [comment]
Cool!

Out of curiosity, does it not use terminfo for a specific reason, such as there not being capabilities for this feature or something like that?

**Comment by iko-deleted** [comment]
It should be trivial to add terminfo support, however the version of terminfo that supports this is only available on a handful of platforms, which doesn't include my laptop. I tried installing a local version, but couldn't figure it out. I'd be able to install it easier in a vm/nix, but for some reason that didn't occur to me until just now.

Even with terminfo support, we'd want to have this option as a backup because of the limited adoption, so I decided to go with the easiest path.

Once I get the newest terminfo installed, it shouldn't take much time at all to add support.

**Comment by cjenn** [comment]
Also, just for my sake, here's a list of things that are left to do:
- [ ] Add detection for the $COLORTERM environment variable
- [ ] Add terminfo support
- [ ] Finalize type/operator names
- [ ] Edit/revise haddocks
- [ ] Profile, check any simple/obvious optimizations I can think of

**Comment by typedrat** [comment]
Any progress on this?

**Comment by iko-deleted** [comment]
This is almost complete. I'll try to get a pr in by the end of the week.

There isn't any real hold-up vty-wise; I just switched to a new computer a couple months ago and more or less forgot about this in the mess.

I was going to work on this yesterday, but I accidentally deleted my wifi driver. I'll get to work on it as soon as my laptop is back to normal.

**Comment by jtdaugherty** [comment]
Thanks for the update, @cjenn!

**Comment by u-quark** [comment]
@cjenn Do we have any updates on this?

The code from @cjenn works fine for me. The only issue is that the detection of 24-bit color support is not working without looking at the `COLORTERM` environment variable additionally to looking at the terminfo capabilities. For context most terminal emulators support this environment variable: https://gist.github.com/XVilka/8346728#true-color-detection

@jtdaugherty I've added a commit that fixes the above issue and created a merge request from @cjenn's code: #182

**Comment by u-quark** [comment]
I need to have a look at the tests because they are failing.

**Comment by u-quark** [comment]
I added a commit to the branch that fixes the tests. I think it makes sense to set config `colorMode` to `NoColor` since the terminals types tested (vt100, vt220, ...) don't support color in general.

**Comment by u-quark** [comment]
@jtdaugherty Do we have any updates on this and #182 ?

**Comment by jtdaugherty** [comment]
@u-quark no. I have not had time to take a closer look at the work on this ticket.

**Comment by jfischoff** [comment]
I'm also interested in this.

**Comment by spacekitteh** [comment]
Can we please get this? Lack of 24 bit colour is the sole thing preventing me from using vty.

**Comment by jtdaugherty** [comment]
@u-quark's work on this is now released in 5.35.
