### ISSUE TITLE
Better support for unicode character width

### ISSUE THREAD

**Issue by u-quark** [jtdaugherty/vty#175]
When `vty` renders emojis it does not compute the right character width for them.

I know that, as discussed [here](https://github.com/matterhorn-chat/matterhorn/issues/125#issuecomment-260158200), there are no guaranties for terminal emulator behaviour but it seems like most implementations now use 2 characters, as specified in later Unicode 9 standard.

It seems that the vendored version of `wcwidth()` in `vty` is old and does not include emojis. I could not find a reliable source for `wcwidth.c` that is maintained. There is some discussion [here](https://gitlab.freedesktop.org/terminal-wg/specifications/issues/9) about using the system version of `wcwidth` that comes with glibc or not, but not conclusion.

I do agree with the [comment here](https://github.com/jtdaugherty/vty/issues/41#issuecomment-21504311) that we need to provide a working version for systems that don't offer `wcwidth` natively. Though I think `vty` could default to the system version when possible. This would mean that we don't need to maintain a separate implementation that will get out of date. That said glibc's `wcwidth` is [known to have issues and to lag behind](https://eev.ee/blog/2015/09/12/dark-corners-of-unicode/#combining-characters-and-character-width) the Unicode standard but we have better guaranties that it will be updated, eventually.

There is a Haskell library that wraps around system `wcwidth` when possible: https://github.com/solidsnack/wcwidth that currently gives the correct result for at least Unicode 11.0/Emoji 11.0/2018 emojis (`vty` version `5.25.1`, `wcwidth` version `0.0.2`, `glibc` version `2.28`):

```haskell
> putStrLn "\x1F355"
🍕
> Graphics.Text.Width.wcwidth '\x1F355'
1
> Data.Char.WCWidth.wcwidth '\x1F355'
2
> putStrLn "\x1F973"
🥳
> Graphics.Text.Width.wcwidth '\x1F973'
1
> Data.Char.WCWidth.wcwidth '\x1F973'
2
```

I am not sure if we want to use that library as we potentially only want a thin wrapper around the C function.

Also I am not sure if we want to use `wcwidth` and count the total width in `vty` for a given string or use `wcswidth` instead?

Depending on responses I am happy to come up with a PR for this.

**Comment by jtdaugherty** [comment]
Thanks for filing this. I'm not exactly sure what the right path forward is, because in my experience, no approach works fully due to the issues you cited. For example, @glguy [had a problem](https://github.com/jtdaugherty/vty/issues/115) where an upgrade to Vty's `wcswidth` C code which ostensibly *fixed* Vty caused breakage for the terminal he was using because its width tables are stale (and are unlikely to get upgraded soon). The conclusion of that discussion suggested the only reasonable (but nonetheless annoying) solution that I know of: let Vty support different implementations of character width computations (hopefully based on Unicode version) and let the Vty application choose, which consequently means exposing that choice to the end user.

**Comment by jtdaugherty** [comment]
I also want to say that while the issue is a thorny one, I very much would love it if we can improve the situation. The Matterhorn project I work on is particularly vulnerable to problems with character width because other Mattermost clients send wide emoji characters on a regular basis.

**Comment by glguy** [comment]
I don't have a solution yet, but I've been using this code to figure out the current terminal's behavior.

I think we could make an executable to generate an efficient `wcswidth` table for each Terminal that we're interested in and let people configure the `vty` package accordingly. The library already has a notion of a user-level configuration file.

**Comment by jtdaugherty** [comment]
I don't yet know if the choice of terminal emulator (and its attendant versions) is a good axis of configuration for Vty, but if it was, I'd be okay with that approach. In particular I don't know whether that makes for a good user experience, and we'd need to do some research on the correspondence between emulator versions and Unicode behavior. Lastly, I'd be concerned that the emulator version is not always a good proxy for Unicode support; in the case of VTE-based emulators like Gnome Terminal, the VTE version is likely to be the version of interest rather than the version of Gnome Terminal itself.

As far as configuration goes, even if Vty is configurable through its configuration file, I'd want to ensure that application developers can configure Vty programmatically without exposing Vty to their users.

**Comment by u-quark** [comment]
Thank you both for your answers! I will think about it and come up with a more concrete proposal.

Some questions:
@jtdaugherty Is it possible for vty to know the terminal (emulator) it is running against, and maybe the version. Is this something that is provided by terminfo maybe?
@glguy What code are you using to determine the terminal behaviour?

**Comment by jtdaugherty** [comment]
> @jtdaugherty Is it possible for vty to know the terminal (emulator) it is running against, and maybe the version. Is this something that is provided by terminfo maybe?

Not that I know of. I believe the only way we can get this information is for the user / application programmer to tell us. This is why my original thinking about this was about configuring based on Unicode version, not terminal emulator -- not because Unicode version is easier to detect (it isn't), but because then we don't have to track emulator versions and associate them implicitly with Unicode versions.

**Comment by jtdaugherty** [comment]
@u-quark @glguy meant to link to this: https://gist.github.com/glguy/a802eaaac5a00ab41e3c3ca33507634b

**Comment by jtdaugherty** [comment]
@glguy and I talked about this in person and concluded that another approach, if a tool based on the gist above is feasible, would be to have that tool interrogate the terminal to generate metadata that Vty-based applications could later load to influence their width computations. That would avoid needing to couple this to Unicode versions (which @glguy says won't be useful because they don't actually specify character widths anyway) or terminal emulators (which has the issues I mentioned before). This would also mean that application developers wouldn't need to worry about this issue at all because it could be done transparently by Vty based on the presence of, say, an environment variable or Vty configuration file.

**Comment by u-quark** [comment]
Thanks for the info. I think the approach that you describe makes sense! I will look into this more and come back to you.

**Comment by u-quark** [comment]
I did a small survey of the behaviour of terminal emulators based on the code from @glguy. Here are my results.

I tested the following terminal emulators on a fairly recent Debian unstable:
 * vte: GNOME Terminal 3.34.0 using VTE 0.58.0 +BIDI +GNUTLS
 * Konsole 19.08.0
 * Kitty 0.14.4
 * mlterm 3.8.8 (Features: otl ssh implugin imagelib(builtin) utmp)
 * urxvt (rxvt-unicode) v9.22 - released: 2016-01-23
 * XTerm 348
 * st 0.8.2

Also on a Mac:
 * iTerm2 3.2.9
 * Terminal.app (did not note the version)

I compared them to each other and to:
 * wcwidth from glibc 2.29-1 on Linux
 * wcwidth from libc on Mac Libsystem-1238.60.2
 * vty 5.25.1 implementation

I tested all the Unicode code points up to `\x2FA1F`. The following table shows in how many characters the different implementations disagree on.

```
             glibc  iterm2  kitty  konsole  maclibc  mlterm  st     terminalApp  urxvt  vte    vty    xterm
glibc        0      672     654    268      17814    497     2      1412         2      83     1412   2
iterm2       672    0       102    474      17785    181     670    2050         670    607    2050   672
kitty        654    102     0      386      17803    247     652    2042         652    571    2042   654
konsole      268    474     386    0        17690    617     266    1664         266    185    1664   268
maclibc      17814  17785   17803  17690    0        17920   17812  17103        17812  17812  17103  17814
mlterm       497    181     247    617      17920    0       495    1879         495    432    1879   497
st           2      670     652    266      17812    495     0      1410         0      81     1410   2
terminalApp  1412   2050    2042   1664     17103    1879    1410   0            1410   1479   0      1412
urxvt        2      670     652    266      17812    495     0      1410         0      81     1410   2
vte          83     607     571    185      17812    432     81     1479         81     0      1479   83
vty          1412   2050    2042   1664     17103    1879    1410   0            1410   1479   0      1412
xterm        2      672     654    268      17814    497     2      1412         2      83     1412   0
```

The code I used with the results can be found in https://gist.github.com/u-quark/fb8540813a3bdccda0d583c61a31f265. Also the character widths for each implementation are [here](https://gist.github.com/u-quark/fb8540813a3bdccda0d583c61a31f265/raw/bc88333b244291034a084cc770801c95476c9875/wcwidths.zip) and the lists of characters that have different width implementations [here](https://gist.github.com/u-quark/fb8540813a3bdccda0d583c61a31f265/raw/bc88333b244291034a084cc770801c95476c9875/compare.zip).

---

A few notes from these results:

Most terminal emulators differ between each other in several cases (vte_kitty.txt). xterm, urxvt and st seem to be in agreement with each other and with glibc (the 2 differences (urxvt_glibc.txt) are in control characters). The other differences can probably be attributed to subtle difference in implementation of various language scripts.

The _good_ news is that these differences seem to be a few cases in various scripts but not disastrously too many and everywhere. Also glibc's wcwidth seem to be doing well across many terminals in Linux. Note also, that most of the differences occur in characters that seem to be supposed to be used in combinations with other characters.

It seems vty's wcwidth has the most incompatibility (vty_vte.txt) in Linux terminals, especially in latest Unicode versions (see emoji). Also it seems there are not many differences between glibc's wcwidth and vty's vendored implementation (vty_glibc.txt) - besides emoji.

Libc that comes with Mac seems to be completely wrong in most cases for both iTerm2 (iterm2_maclibc.txt) and Terminal.app (terminalApp_maclibc.txt).

vty's implementation seems to agree fully with Terminal.app. They both seem to assume wcwidth for a lot of wide characters to be one column.

@glguy Which terminal emulator/version did you use when you had issues using utf8proc in vty? What was the problem you had?

---

Based on this I think we could do the following (building on what you suggested before):

1) Have a file that configures how vty behaves with respect to terminal emulator behaviour. The path to this file can be read from an environment variable, say `VTY_CONFIG` and can default to `$XDG_CONFIG_HOME/vty/config`. This way this config can be overridden for different terminal emulators.

2) If the file is not present the first time a vty application starts we run some tests to determine the terminal behaviour and initialize the file. Any subsequent runs of vty applications are configured from the file without any tests. This way the end user will have a good experience without needing to run another tool before using the vty application and will still have good defaults in most cases.

3) We provide three ways of handling wcwidth in vty: a) the existing vendored implementation, b) an updated vendored implementation that returns 2 for newer wide characters according to the latest Unicode (especially emoji), c) use system's glibc. We make the config initialization process query the terminal behaviour and pick the implementation that fits best. On Mac we pick (a) or (b) based on the character width of an emoji and on Linux if glibc matches the character width we use option (c) or else (a) or (b) accordingly. This way we use the fast and future compatible implementation (c) when it is available.

4) For now only save in vty's config which one of the above tree implementations to use for wcwidth. This is enough to solve this issue easily/quickly and we have the infrastructure to improve the solution in the future to be even more compatible with terminal emulators.

**Comment by glguy** [comment]
vty already has an existing configuration file that we could extend.

I don't remember which characters broken last time we tried using utf8proc's implementation with vty, but I do remember noticing a lot more errors in Terminal.app in IRC channels at that time. I would guess it had to do with emojis but I don't remember. It's likely that this was on an earlier version of macOS than the current release and Terminal.app might have changed in the meantime.

Vty disagrees with Terminal.app on a bunch of characters. One example is U+2B50 (⭐) a wide character that vty considers to have width 1. By my count it differs on 1700 characters. That's to say I don't understand what you meant about vty agreeing with Terminal.app

**Comment by u-quark** [comment]
We should use the existing configuration file, as you suggest.

I probably copy-pasted the wrong file for Terminal.app. Can you share the file you got from Terminal.app so we have all the information in one place?

Do you think overall this is a good solution? Especially if you had problem with emoji before this should address that. I think we can give it a try and test it on a few machines to see if you have any problems.

**Comment by jtdaugherty** [comment]
@u-quark thanks for all of your work on this, that's fantastic! A few comments:

> If the file is not present the first time a vty application starts we run some tests to determine the terminal behaviour and initialize the file

Assuming I understand what you have in mind, I think this would be okay as an application-driven behavior, but *not* as an automatic Vty library behavior. The tests we'd need to run would take time and lead to a confusing startup delay of the application. So if Vty were to provide functionality to perform this testing and generate the config (or a function to mutate an existing config) that the application could call, I think that would work well.

> On Mac we pick (a) or (b) based on the character width of an emoji and on Linux if glibc matches the character width we use option (c) or else (a) or (b) accordingly.

I'm not sure I understand what you mean here. When would this choice of implementation be made? And isn't there a bootstrapping problem? We don't know the width until we ask these implementations, so we can't use the width to choose between them.

**Comment by u-quark** [comment]
> Assuming I understand what you have in mind, I think this would be okay as an application-driven behavior, but _not_ as an automatic Vty library behavior. The tests we'd need to run would take time and lead to a confusing startup delay of the application. So if Vty were to provide functionality to perform this testing and generate the config (or a function to mutate an existing config) that the application could call, I think that would work well.

That makes sense and we can figure out what the better default config is later. That said I am hoping that the checks are almost instant and imperceptible.

> I'm not sure I understand what you mean here. When would this choice of implementation be made? And isn't there a bootstrapping problem? We don't know the width until we ask these implementations, so we can't use the width to choose between them.

The choice of the implementation would be done when you initialize the configuration after the tests mentioned above, and based on their results. When I say "based on the character width of an emoji" I mean the observed width from the terminal as returned by `getCursorPosition0` from our test. After the decision is made of which implementation to use and saved to the vty config we always use that implementation.

**Comment by jtdaugherty** [comment]
> That said I am hoping that the checks are almost instant and imperceptible.

I'm not sure we are talking about the same thing by "the checks" here. Above, I proposed that if we are going to use @glguy's tool functionality to determine what the local terminal thinks about Unicode characters, it would be good to make a tool that users can run that saves the results of the time-consuming analysis. Then, Vty would load that saved data and use it as an alternative to a width function like `wcwidth`. Do you mean something else?

> The choice of the implementation would be done when you initialize the configuration after the tests mentioned above, and based on their results

Yeah, I think this is where the confusion is. Based on my suggestion above, there is no implementation selection at all, because the saved data is used instead. The implementation still matters, but only when there's no saved character width map to load. Does that make sense?

**Comment by u-quark** [comment]
> Above, I proposed that if we are going to use @glguy's tool functionality to determine what the local terminal thinks about Unicode characters, it would be good to make a tool that users can run that saves the results of the time-consuming analysis. Then, Vty would load that saved data and use it as an alternative to a width function like wcwidth.

What I don't like about this approach is that if an application uses emoji regularly it is going to be broken from the beginning. Requiring the user of this application to first run some other script that is going to take ~2h is not a very good experience. Same for having to write a configuration file. That's why I propose having a few build-in implementations and choosing the most compatible by doing a mini test on the first run of the application only with the intention to fix emoji. As I mentioned before this mini test can by done by the application and not by vty.

**Comment by jtdaugherty** [comment]
> What I don't like about this approach is that if an application uses emoji regularly it is going to be broken from the beginning.

Why would this be the case? As I understand it, using the tool mentioned above would prevent this.

> Requiring the user of this application to first run some other script that is going to take ~2h is not a very good experience.

I agree.

> That's why I propose having a few build-in implementations and choosing the most compatible by doing a mini test on the first run of the application only with the intention to fix emoji.

What would the "mini test" be?

**Comment by u-quark** [comment]
> > What I don't like about this approach is that if an application uses emoji regularly it is going to be broken from the beginning.
> 
> Why would this be the case? As I understand it, using the tool mentioned above would prevent this.

Because there is the caveat mentioned below. If the user does not use the tool mentioned above then they will have a broken experience.

> > Requiring the user of this application to first run some other script that is going to take ~2h is not a very good experience.
> 
> I agree.

---
> > That's why I propose having a few build-in implementations and choosing the most compatible by doing a mini test on the first run of the application only with the intention to fix emoji.
> 
> What would the "mini test" be?

I assume we can look at the width of a single emoji (or maybe two) using @glguy code and assume that the rest behave the same way.

**Comment by jtdaugherty** [comment]
> I assume we can look at the width of a single emoji (or maybe two) using @glguy code and assume that the rest behave the same way.

Since there are many emoji added in each Unicode version, there is no single emoji that will predict how the terminal will behave for the rest. The terminal can also freely implement only part of the character ranges for each Unicode version, meaning that we can't rely on the terminal's behavior with one character in a particular version to represent how the terminal will handle others.

**Comment by u-quark** [comment]
> Since there are many emoji added in each Unicode version, there is no single emoji that will predict how the terminal will behave for the rest. The terminal can also freely implement only part of the character ranges for each Unicode version, meaning that we can't rely on the terminal's behavior with one character in a particular version to represent how the terminal will handle others.

Ok, what could we do instead then?

**Comment by jtdaugherty** [comment]
As far as I can tell, there are two extremes:

* Extreme A: Do nothing, and things will continue to work (or not work) as they do right now. This approach means the level of brokenness will vary based on the factors you covered in your analysis above.
* Extreme B: poll the terminal to get its width for as many wide Unicode code points as possible. This approach can be exhaustive and give good behavior, but it has the downside that it could be time-consuming and requires users to run an extra tool.

I've been advocating for Extreme B, partly because back when @glguy first made his tool I had the impression it didn't take *that* long to run. I don't remember exactly how long it took, though, or how many code points it queried. You mentioned two hours in your comment above - what is that number based on? If I recall, @glguy's script only took a few minutes.

The reason I'm glad you've spent so much time researching this is that I also don't like Extreme A. The emoji issue bites us routinely on the `matterhorn` project, and it sucks to not have a good story for this problem whenever it comes up. @glguy runs into this on his `glirc` project, too, so we are both interested in making progress on this.

As I see it, there are other options in between these two extremes like ones you have outlined here, where we make a better effort than we're currently making to get this right. I've been pushing for a more aggressive approach under the assumption that it's not that onerous for users, considering that right now things seem to work more or less okay, most of the time, for most people, as far as I know. As I see it, if running an extra tool that completely eliminates this problem is too much burden, not running the tool is a pretty acceptable solution if the fallback behavior is today's behavior.

Granted, making an extra tool also means we need to maintain it, and it means that tool needs to be available in binary form for as many platforms as we can support because we won't want to expect users to build Haskell programs from source. And supporting such a tool on a bunch of platforms is a lot of work and requires a bunch of resources. So I'd also want to be sure it was worth it before going to all of that trouble.

**Comment by jtdaugherty** [comment]
I'll also add that a hybrid approach is also possible. Users who want to run the tool that will generate the 100% correct database of widths can always do so, and users who don't want that can rely on the library's smart choice of width implementation to get it right more of the time than Vty currently does.

In that case, though, I still want to figure out how that implementation will be selected. @u-quark gave a logic outline above, but I don't know what evidence we can use to choose from amongst them since as far as I can tell, sampling character widths won't tell us which one is the better one to use.

**Comment by u-quark** [comment]
So, I finally got some time to come back to this and to write some code for it.

See #179 for my take on it. I've tested it on a few terminals and it seems to work pretty well. I haven't tested this on Mac. Please provide specific examples if/where this breaks for you, possibly using `vty-wcwidth-tester` utility.

This implementation, of course, is not perfect. But I think, if #179 is not controversial, we can merge it and continue discussing this issue here. #179 already fixes most of the issues I've seen.

**Comment by jtdaugherty** [comment]
@u-quark - thank you for your work on this! I have once again gotten time to come back around to this. After thinking on the results of your investigation and #179, and after talking about some concerns we had, @glguy and I are going to take new approach which I'll detail below. Consequently I'm going to close your pull request, although some of the work you did there will be migrated over (in particular, the tool to determine character widths). And the new approach is a hybrid based on ideas we have discussed on this ticket.

Here's what we have in mind now:

1. We'd like to avoid automatic character width table-generation for a number of reasons, so instead of having the library generate a table at startup by default, the library will use its built-in logic for computing widths instead. Put another way: unless told to do otherwise, it will do what it does now, and consult some width function that is compiled in.
2. The library will ship with a command-line tool to query the terminal for character widths. It will have the ability to write the results of that query to a binary file for later loading by the library. The format of the file will be a run-length encoding of the answers that the terminal gave; in particular, it will be a series of nine-byte sequences, the first four bytes indicating the starting code point of a range, the second four bytes indicating the end code point of a range, and the final byte indicating the column count for the characters in that range. The binary format will also have a header indicating the format version.
3. The table-generation logic used in (2) should also be exposed in the library API so that applications that want to invoke that logic can do so programmatically.
4. The library will provide an API for loading the tables described in (2). The library will also provide an API for installing the loaded tables into the address space of the Vty application for later consultation by the C width routine. The Vty library's API for installing tables should be thread-safe. Providing this API makes it possible for Vty's width functions to be used without using the rest of the Vty library to take control of the terminal, which may be important. (In particular, applications that need Vty's functions but that don't want to invoke `mkVty` will need this functionality; see below.)
5. The C width function will consult a global table pointer to determine whether a custom table has been installed. If the pointer is NULL, the built-in logic (i.e., today's logic) will be used to compute character widths. Otherwise the built-in table will be consulted. The in-memory table will be a contiguous C array whose indexes are code points and whose values are bytes indicating the column count for each code point. This is not the most memory-efficient, but it's easy to replace with a more efficient implementation later (e.g. 2 bits per code point, or 16 code points per array slot, say).
6. The Vty configuration file will be equipped with a new line syntax to allow users to indicate that Vty should automatically load and install particular tables based on the value of TERM. The `mkVty` function and its relatives that read the Vty configuration will be responsible for loading and installing the tables mentioned in the config. This is mostly to support applications like `tmux` and `screen`. But it also makes it easy to use the same Vty application on a system with different terminal emulators. The syntax will be something like `width_map <TERM> <PATH>`. If these lines are absent, or if they cannot be honored due to I/O errors, the default built-in width mapping will be used.

@glguy If I missed anything, let me know and I can edit.

**Comment by jtdaugherty** [comment]
My work on this will be happening on the `feature/unicode-tables` branch.

**Comment by jtdaugherty** [comment]
Steps (2) and (3) above are now complete.

**Comment by jtdaugherty** [comment]
As of 74a7c557fb895e8dc5bd739d2e27cb243f18d5b1, (4) and (5) are now complete, with some caveats:

* Rather than provide a thread-safe, general API for swapping tables, @glguy and I decided to support at most one custom table installation. The reasoning is detailed in the commit log.
* The `wcwidth` function is pure, but behaves impurely once a custom table has been installed. The reasoning for this is spelled out in the documentation for the newly-added functionality.

**Comment by jtdaugherty** [comment]
As of 9edfd029cb5275b7d2e43d83e2487e46c9d02c98, (6) is now complete.

**Comment by u-quark** [comment]
@jtdaugherty All of this plan seems good! Except for one point. The default built-in behaviour. When someone tries one of the vty application they will not run some other command line tool to fix their broken layout. They will just assume that the application is broken. I see no reason for not switching the default implementation to the on from #179 if it makes things better.

**Comment by glguy** [comment]
If we have configurable tables I think it makes sense to update the default table if it actually is a better default

**Comment by jtdaugherty** [comment]
> I see no reason for not switching the default implementation to the on from #179 if it makes things better.

I agree that switching the default implementation to a different one is worth doing if the new implementation results in more correct answers about widths, more of the time, with most terminal emulators. What I don't know is how to determine whether a new implementation actually *is* better. In the past, I've upgraded the `wcwidth` implementation in `vty` only to find that it actually made things worse, since it made the disagreement with the terminal emulator larger. That led me to conclude that the "best" thing to do for the time being is to keep the `wcwidth` implementation in `vty` at a similar level of staleness as the ones in most terminal emulators, since that generates a smaller disagreement about widths.

**Comment by u-quark** [comment]
I would agree but:

1. A few years have passed since that decision and terminal emulators have been updated.
2. The short survey I did seems to suggest that the new implementation performs better.

Maybe you could try the implementation in #179  on a few terminals that you had problems with last time and see how it performs so that we get a better idea.

**Comment by jtdaugherty** [comment]
I haven't commented on the specific merits of the implementation in #179 because I've been focused on the bigger issues with the approach we've discussed in this ticket. With that said, I am not excited about merging the implementation in #179 because I'm not sure I trust the provenance of it (Musl is a great library for what it is but strikes me as a strange choice for where to borrow this from), I think its implementation is *significantly* more inscrutable than the current one, and I don't think the data you gathered above (as nice as it is!) makes the amount of improvement clear enough to make it the obviously-right choice.

If I was going to consider upgrading the built-in implementation again, I would much more prefer to use `utf8proc` because it is a well-maintained library specifically intended to be used for this kind of problem.

**Comment by jtdaugherty** [comment]
As of 16d5f27832ed04e77aefb9430473ee64c07c547b, the `Config` has a field `allowCustomUnicodeWidthTables` (defaulting to `True`) that allows a Vty user to suppress custom table loading that `mkVty` will now do when it finds a custom table declared in the Vty configuration file.

At this point I've also tested the custom table functionality with [matterhorn](https://github.com/matterhorn-chat/matterhorn) with excellent results: once a custom table has been generated, Matterhorn transparently loads that and successfully renders wide characters that it previously had trouble with.

@glguy would it be possible for you to try out the `feature/unicode-tables` branch with `glirc`?

**Comment by u-quark** [comment]
I do agree the implementation based on musl code is more complex compared to the one currently in vty. The reason is performance and space of the Unicode tables. The implementation is using a two step lookup in C arrays so that it balances quick lookup with size of the produced binary (the array stored in code). I don't pretend I fully understand it. The existing code in vty is using a binary search, if I remember correctly. Given that wcwidth in vty is used during every operation is makes sense to keep the C function fast.

I am not too fuzzed about which implementation to use as the default built-in, as long as it gives the right answer according to Unicode for emojis.

> I don't think the data you gathered above (as nice as it is!) makes the amount of improvement clear enough to make it the obviously-right choice.

What can we do to gauge the impact of changing the default implementation? How can we collect more data to make an informed decision?

> If I was going to consider upgrading the built-in implementation again, I would much more prefer to use `utf8proc` because it is a well-maintained library specifically intended to be used for this kind of problem.

I could have a look at porting to vty the implementation of character width in `utf8proc`, if you think that would be valuable.

**Comment by jtdaugherty** [comment]
> What can we do to gauge the impact of changing the default implementation? How can we collect more data to make an informed decision?

I'm not sure, really. Your findings above suggest that this is even more of a moving target than I originally thought, since the amount of computation/emulator disagreement is all over the place. The most exhaustive way to gauge the impact of a change in implementation would be to run the tests you ran above, but on all of the emulators we anticipate people will use. That's impractical. I think the only way to make this option realistic is to greatly constrain the set of emulators tested against, and even then, that requires access to testing systems to gather the data. Finally, this option assumes that compatibility is non-decreasing as terminal emulators evolve; I'm not sure that's safe to assume, since a newer release of a width computation may work better with many emulators and worse with others.

The other extreme is to upgrade the implementation purely based on its own merit. So, for example, if the latest version of `utf8proc` claims that it properly supports all of known Unicode at any given time, that makes it a good choice. However, the problem with this reasoning (as experienced directly by @glguy) is that a perfect width computation is not helpful if the terminal emulators lag behind and disagree, leading to behavior that is no better than what we have today.

Neither of those options seems like a great one to me. However, now that we have a pretty good story for how to deal with the compatibility issues, I think it's less of a problem. That does mean application developers (such as myself) will have to figure out how to make it easy for users to benefit from this new functionality, such as by distributing the Vty command-line tool that builds custom tables or by integrating it into their applications.

> I could have a look at porting to vty the implementation of character width in utf8proc, if you think that would be valuable.

Since I have taken that approach before, I would be happy if we took it again. (I am willing to break things for the right reasons, and we have a good fallback plan if that happens.) I would like to know what @glguy thinks about it, first, though.

**Comment by u-quark** [comment]
@jtdaugherty Your points are all valid. I do agree that testing the impact of the change is difficult, I also agree that the solution with loading external pre-computed tables is a good one and it solves all the problems for regular users. I am very happy we are seeing progress in this ticket. After @glguy's input and if you are still on board with the idea, I think it is a good ito give `utf8proc` another go. I had a brief look and it is not easy to separate the code for character widths from the rest of library. So we could either vendor it or depend on the system version of it.

**Comment by jtdaugherty** [comment]
The work in this ticket is now complete and has been released in `5.28`. Thanks @u-quark and others for your persistence in helping us work on this ticket!

**Comment by u-quark** [comment]
Thanks for all your work @jtdaugherty !

**Comment by jquast** [comment]
Hello,

I know this issue is closed, forgive me. But, about your statements @jtdaugherty,

> this is even more of a moving target than I originally thought, since the amount of computation/emulator disagreement is all over the place. The most exhaustive way to gauge the impact of a change in implementation would be to run the tests you ran above, but on all of the emulators we anticipate people will use.

I have authored a [specification](https://wcwidth.readthedocs.io/en/latest/specs.html) for the python wcwidth library, and an automatic testing tool, [ucs-detect](https://ucs-detect.readthedocs.io/intro.html#installation-usage), that asses each terminal emulator's compliance, and then I have gone ahead and performed testing on 20+ popular terminals and [reported their results](https://ucs-detect.readthedocs.io/results.html)

I hope this is helpful, I have also written an article about this work https://www.jeffquast.com/post/ucs-detect-test-results/

**Comment by jtdaugherty** [comment]
@jquast thanks, I will take a look!
