### ISSUE TITLE
Additional Mouse Buttons

### ISSUE THREAD

**Issue by qcc-na** [jtdaugherty/vty#180]
Would it be possible to add support (if there isn't already) for Mouse4 and Mouse5 buttons?  These are typically associated with back and forward buttons on more modern mice.  My use case is a browserlike application with historical navigation, aka going back and forth between pages.  Ultimately I'd use this functionality through brick.

https://i.stack.imgur.com/FdVVN.png
![image](https://user-images.githubusercontent.com/47015534/68078866-272de700-fdad-11e9-98ea-5521728ff28f.png)

**Comment by glguy** [comment]
Do you know of a terminal that supports this? As far as I know neither Terminal.app nor iTerm support it, for example.

**Comment by jtdaugherty** [comment]
@qcc-na The reason Vty doesn't support additional mouse buttons is because the control sequences we get from the terminal don't include that information. Only two bits are used to represent the mouse buttons involved, so we can't support more than three. You can find more details here:

https://unix.stackexchange.com/questions/518479/complex-mouse-inputs-in-xterm
