### ISSUE TITLE
Clarify "escape" wording in documentation.

### ISSUE THREAD

**Issue by stephen-smith** [jtdaugherty/vty#186]
At https://github.com/jtdaugherty/vty/blob/master/src/Graphics/Vty/Image.hs#L141 and in other places both in the Vty and the Brick documentation you mention a string "containing escapes".

Do you mean that it literally cannot contain the [U+001B codepoint](https://www.fileformat.info/info/unicode/char/001B/index.htm) and all other Unicode scalars are fine, or are there other Unicode scalars that I need to avoid?  (C0/C1 characters or Unicode control characters, LTR/RTL override characters, are among the other things I'm worried about.)  I'm probably thinking about this too much, but I'm trying to display something fetched over the network from a location specified by the user, and I'd like to know exactly how little processing I can get away with between wreq and Brick.

**Comment by jtdaugherty** [comment]
I'm happy to update the docs. To answer your question here, though: yes, "escapes" in the Vty/Brick docs refers to ASCII 27, or Unicode U+001B. The reason is that Vty manages attributes itself and if you provide a string containing your own escape sequences, Vty makes no guarantee at all about the resulting on-screen representation in terms of either attributes or layout. The same goes for carriage returns.

**Comment by jtdaugherty** [comment]
The haddocks in `master` are now updated. Thank you!

**Comment by jtdaugherty** [comment]
Also relevant: https://github.com/jtdaugherty/brick/commit/5b94b596c4e8a0e43f241160ee741767b498ab34

**Comment by stephen-smith** [comment]
Wow!  Thanks for amazingly fast response!
