### ISSUE TITLE
Joining widgets - additional use case.

### ISSUE THREAD

**Issue by mkloczko** [jtdaugherty/vty#218]
For more freeform widget composition.

An example:

```
  +---+
  | 1 |
  |   +-+
+-+---+2|
| 3 | +-+        <- this might be problematic
+---+-------+
    |   4   |
    +-------+
```    

I'm not sure if the above is doable using vertical/horizontal joins, as if 1 and 2 were joined, then with 3, and then with 4, it should look like:

```
    +---+
    | 1 |
    |   +-+
+---+---+2|
| 3 |   +-+        
+---+-------+
    |   4   |
    +-------+
```

**Comment by jtdaugherty** [comment]
This *might* be possible in a single layer with some clever translations (`translate`, `translateX`, and `translateY`), but I'm not sure about that.

It is *definitely* possible to do this in multiple layers with translations. Have you tried that kind of approach?

**Comment by mkloczko** [comment]
Yes, it's just I didn't design my code right now to use multiple layers per widget. But maybe that's the way.

Right now I'm writing a function that takes two widgets (and some additional data like size and offset) and returns another widget (with additional data). 

I think about dividing the area into tic/tac/toe grid and then selecting where the original widgets appear, if there's an area where two widgets are to be drawn together either overlap or fill with some kind of character.

**Comment by jtdaugherty** [comment]
Cool! I think multiple layers with translations will be the best way to go for now. I haven't the faintest idea how it could be done otherwise; I'm having a hard time imagining what an API would look like to allow the construction of concave structures like the example you gave above. Since I don't see a path forward on that, and since the layering approach should be adequate for now, I'm going to close this. But if you think about it more and have ideas for an API, let me know!

**Comment by mkloczko** [comment]
Ok, thanks. I've got some ideas, will probably come back to this tomorrow with some code. I'll just add my 2c to the layers thingy (I'm assuming we're talking about bricks layer) - it would be nice to have the possibility to write a library of more complex widgets without thinking about the layering system for a given application. There could be both a internal layering system for more complex widgets and the bricks layering system.

It could probably work by adding an additional node to the Image data-type, which would contain some more stateful code. API -  a call taking two widgets and an offset? I don't know, I'll come back with a proof of concept soonishly.

**Comment by jtdaugherty** [comment]
Okay, keep me posted.

I noticed that you mentioned "brick" a few times, and have used the term "widgets;" did you intend to file this on the `brick` repository instead? Vty is lower-level and needs to stay that way. Brick provides a higher-level API and is potentially a better place to explore richer abstractions involving Vty images.

**Comment by mkloczko** [comment]
I plan to use this in brick, yes, but Widgets render Images (ok, now reread the code, vty has layer support for Pictures). The advantage of both Widgets and Images is that they can both be combined, using hJoins, vJoins, and have all the existing machinery for coloring and styling. Since this is more related to Images i went here with the idea.

**Comment by mkloczko** [comment]
Here's the idea: 

https://gist.github.com/mkloczko/dd33c42867272727d7dd7cc8e5ec0885

It's tad stateful and not very Haskell like. Works on Widgets but should be doable for Images (crops and images as internals are used). 

Anyway just wanted to share the idea - imo it does it's job well, but I'm not sure how could this work with Widgets/Image internals (size constraints, calculating offsets, etc), so I pass them outwardly. Could probably be done on images themselves.

EDIT: _grid references the widget to be drawn at certain place in the grid (with the help of _xAxes and _yAxes). There's ```cut1-4``` and ```joined``` cuttables that can be drawn. And there's the ```mymain``` that does the drawing.

**Comment by jtdaugherty** [comment]
Nice! I took a look. I can't say for sure without looking more closely, but you might be able to avoid having to provide width and height info to `createCuttable` by 1) building up abstract `Cuttable` terms rather than evaluating at creation or join time and 2) making `drawCuttable` a custom widget that evaluates the `Cuttable` terms, rendering the sub-widgets, and using their dimensions to them further decide on how to do joins, etc.

**Comment by mkloczko** [comment]
Isn't rendering the sub-widgets a bit slow? I mean, you have to render them and then put them back into the widget itself to be rendered again... I've did a table once like that and it was tad slow. 

But it's probably not slower than this approach. Thank you for the feedback!

**Comment by jtdaugherty** [comment]
> Isn't rendering the sub-widgets a bit slow?

They need to get rendered anyway, don't they?

> I mean, you have to render them and then put them back into the widget itself to be rendered again... I've did a table once like that and it was tad slow.

Widgets should only get rendered once; you can avoid a double-render by keeping the `Result` from a rendering around, which you can then embed as you wish. You would have to go to some trouble to render something twice, because you'd have to do it inside the `RenderM` monad and then just throw away the result. If you have questions about this, let me know!

**Comment by jtdaugherty** [comment]
There's some info here, which I could expand if needed:

https://github.com/jtdaugherty/brick/blob/master/docs/guide.rst#implementing-custom-widgets

**Comment by mkloczko** [comment]
Ok, thanks, will look at this and the old table code to see what went wrong.

**Comment by jtdaugherty** [comment]
I don't know how well my implementation will correspond with yours, but you might also consider looking at [the source](http://hackage.haskell.org/package/brick-0.60.2/docs/src/Brick.Widgets.Table.html).
