### ISSUE TITLE
Potential Bug (mkVty on ghci)?

### ISSUE THREAD

**Issue by liamzee** [jtdaugherty/vty#263]
On ghci (ArchLinux, Konsole), trying foo <- mkVty defaultConfig results in terminal corruption, as vty starts eating inputs and causing weird behavior in the particular console.

Not sure if this is acceptable behavior, since mkVty documents "at most one handle should be made per terminal device", but vty has made no terminal devices, it's just clashing with ghci.

**Comment by jtdaugherty** [comment]
Hi @liamzee - this is expected behavior, and basically the issue is that `mkVty` is specifically for when you want to *take control of the terminal* and only use Vty to interact with it. So I don't recommend using `mkVty` in `ghci` because `ghci` already has control of the terminal: it is already in the process of accepting input and printing output. So you'll get exactly the result you see, which is two programs basically fighting over the terminal.
