### ISSUE TITLE
importing Vty interferes with GHCI input, requires two keypresses

### ISSUE THREAD

**Issue by simonmichael** [jtdaugherty/vty#85]
While stepping through code similar to [this](https://github.com/simonmichael/hledger/blob/74512814eca6b66f74edbeac8a28dc96fd555371/hledger-ui/Hledger/UI/Main.hs#L10), I notice that after app (defined at line 84) is evaluated, GHCI ignores every second keypress. You can still work it, but you have to press every key twice. I assume it's due to some event handler installed (already ?) by Vty. It would be very helpful if this could be prevented when debugging. (ghc 7.10.2, vty-5.3.1, brick-0.2, osx and gnu/linux)

**Comment by coreyoconnor** [comment]
Your analysis seems correct: On initializing the input layer vty starts an input processing thread. Unless `shutdown` is called the input thread will still be active. When a Vty is initialized again a new input thread will be forked. The multiple key presses are required likely due to a race between the two input threads.

As for resolution: I'm not sure how best to treat this. The stdin handle for a terminal is stateful and requires blocking IO to process the input correctly. Not aspects that are friendly to Haskell. Even in the IO monad. The requirement here is: The `shutdown` destructor should be invoked without an explicit request.

The only route I see right now is using a ForeignPtr to associate `shutdown` with the finalizer of a ForeignPtr. Assuming the ForeignPtr is finalized prior to the next Vty initialization this would work. Which is a rather large assumption. The ForeignPtr docs only guarantee the finalizer is invoked prior to normal program termination.

Looking into other options before investigating using ForeignPtr finalizers.

**Comment by simonmichael** [comment]
It was extra surprising because I though "I have not called any Vty code yet - just imported it to use one of its types". Thinking about it now I suppose I was debugging code that does initialise Vty "later" and GHC has optimised it to be "now".

**Comment by jtdaugherty** [comment]
Realistically speaking, I am not going to get around to this so I'm closing it to avoid staleness. If someone becomes interested in contributing this, we can re-open.
